CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260820060134_Initial') THEN
    CREATE TABLE audit_logs (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        user_id uuid,
        action character varying(100) NOT NULL,
        entity character varying(100) NOT NULL,
        entity_id character varying(100),
        metadata_json text,
        created_at timestamp with time zone NOT NULL,
        CONSTRAINT "PK_audit_logs" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260820060134_Initial') THEN
    CREATE TABLE documents (
        id uuid NOT NULL,
        title character varying(300) NOT NULL,
        source character varying(200) NOT NULL,
        tags character varying(500),
        created_at timestamp with time zone NOT NULL,
        CONSTRAINT "PK_documents" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260820060134_Initial') THEN
    CREATE TABLE users (
        id uuid NOT NULL,
        full_name character varying(200) NOT NULL,
        email character varying(320) NOT NULL,
        password_hash character varying(255) NOT NULL,
        created_at timestamp with time zone NOT NULL,
        updated_at timestamp with time zone NOT NULL,
        is_active boolean NOT NULL DEFAULT TRUE,
        CONSTRAINT "PK_users" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260820060134_Initial') THEN
    CREATE TABLE document_chunks (
        id uuid NOT NULL,
        document_id uuid NOT NULL,
        chunk_index integer NOT NULL,
        content text NOT NULL,
        embedding real[],
        created_at timestamp with time zone NOT NULL,
        CONSTRAINT "PK_document_chunks" PRIMARY KEY (id),
        CONSTRAINT "FK_document_chunks_documents_document_id" FOREIGN KEY (document_id) REFERENCES documents (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260820060134_Initial') THEN
    CREATE TABLE businesses (
        id uuid NOT NULL,
        user_id uuid NOT NULL,
        name character varying(200) NOT NULL,
        type integer NOT NULL,
        category character varying(100) NOT NULL,
        starting_year integer NOT NULL,
        currency character varying(8) NOT NULL DEFAULT 'BDT',
        monthly_opex numeric(18,2) NOT NULL DEFAULT 0.0,
        current_cash_buffer numeric(18,2) NOT NULL DEFAULT 0.0,
        created_at timestamp with time zone NOT NULL,
        updated_at timestamp with time zone NOT NULL,
        CONSTRAINT "PK_businesses" PRIMARY KEY (id),
        CONSTRAINT "FK_businesses_users_user_id" FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260820060134_Initial') THEN
    CREATE TABLE refresh_tokens (
        id uuid NOT NULL,
        user_id uuid NOT NULL,
        token character varying(255) NOT NULL,
        expires_at timestamp with time zone NOT NULL,
        created_at timestamp with time zone NOT NULL,
        revoked_at timestamp with time zone,
        replaced_by_token character varying(255),
        CONSTRAINT "PK_refresh_tokens" PRIMARY KEY (id),
        CONSTRAINT "FK_refresh_tokens_users_user_id" FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260820060134_Initial') THEN
    CREATE TABLE financial_snapshots (
        id uuid NOT NULL,
        business_id uuid NOT NULL,
        period_start timestamp with time zone NOT NULL,
        period_end timestamp with time zone NOT NULL,
        total_income numeric(18,2) NOT NULL,
        total_expenses numeric(18,2) NOT NULL,
        net_cash_flow numeric(18,2) NOT NULL,
        cash_buffer numeric(18,2) NOT NULL,
        outstanding_debt numeric(18,2) NOT NULL,
        health_score numeric(6,2) NOT NULL,
        health_status integer NOT NULL,
        created_at timestamp with time zone NOT NULL,
        CONSTRAINT "PK_financial_snapshots" PRIMARY KEY (id),
        CONSTRAINT "FK_financial_snapshots_businesses_business_id" FOREIGN KEY (business_id) REFERENCES businesses (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260820060134_Initial') THEN
    CREATE TABLE loans (
        id uuid NOT NULL,
        business_id uuid NOT NULL,
        lender character varying(200) NOT NULL,
        principal numeric(18,2) NOT NULL,
        annual_interest_rate numeric(8,4) NOT NULL,
        term_months integer NOT NULL,
        start_date timestamp with time zone NOT NULL,
        created_at timestamp with time zone NOT NULL,
        CONSTRAINT "PK_loans" PRIMARY KEY (id),
        CONSTRAINT "FK_loans_businesses_business_id" FOREIGN KEY (business_id) REFERENCES businesses (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260820060134_Initial') THEN
    CREATE TABLE recommendations (
        id uuid NOT NULL,
        business_id uuid NOT NULL,
        title character varying(200) NOT NULL,
        body character varying(2000) NOT NULL,
        severity character varying(20) NOT NULL,
        created_at timestamp with time zone NOT NULL,
        CONSTRAINT "PK_recommendations" PRIMARY KEY (id),
        CONSTRAINT "FK_recommendations_businesses_business_id" FOREIGN KEY (business_id) REFERENCES businesses (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260820060134_Initial') THEN
    CREATE TABLE simulations (
        id uuid NOT NULL,
        business_id uuid NOT NULL,
        requested_amount numeric(18,2) NOT NULL,
        purpose character varying(200) NOT NULL,
        repayment_term_months integer NOT NULL,
        sales_change_percent numeric(8,2) NOT NULL,
        projected_revenue numeric(18,2) NOT NULL,
        projected_expenses numeric(18,2) NOT NULL,
        projected_cash_flow numeric(18,2) NOT NULL,
        monthly_repayment_burden numeric(18,2) NOT NULL,
        projected_cash_buffer numeric(18,2) NOT NULL,
        recommended_min_amount numeric(18,2) NOT NULL,
        recommended_max_amount numeric(18,2) NOT NULL,
        risk_level integer NOT NULL,
        reasons_json text NOT NULL,
        created_at timestamp with time zone NOT NULL,
        CONSTRAINT "PK_simulations" PRIMARY KEY (id),
        CONSTRAINT "FK_simulations_businesses_business_id" FOREIGN KEY (business_id) REFERENCES businesses (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260820060134_Initial') THEN
    CREATE TABLE transactions (
        id uuid NOT NULL,
        business_id uuid NOT NULL,
        type integer NOT NULL,
        category integer NOT NULL,
        amount numeric(18,2) NOT NULL,
        description character varying(500) NOT NULL DEFAULT '',
        occurred_at timestamp with time zone NOT NULL,
        created_at timestamp with time zone NOT NULL,
        updated_at timestamp with time zone NOT NULL,
        CONSTRAINT "PK_transactions" PRIMARY KEY (id),
        CONSTRAINT "FK_transactions_businesses_business_id" FOREIGN KEY (business_id) REFERENCES businesses (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260820060134_Initial') THEN
    CREATE TABLE loan_payments (
        id uuid NOT NULL,
        loan_id uuid NOT NULL,
        amount numeric(18,2) NOT NULL,
        paid_at timestamp with time zone NOT NULL,
        notes character varying(500) NOT NULL,
        CONSTRAINT "PK_loan_payments" PRIMARY KEY (id),
        CONSTRAINT "FK_loan_payments_loans_loan_id" FOREIGN KEY (loan_id) REFERENCES loans (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260820060134_Initial') THEN
    CREATE INDEX "IX_audit_logs_user_id" ON audit_logs (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260820060134_Initial') THEN
    CREATE UNIQUE INDEX "IX_businesses_user_id" ON businesses (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260820060134_Initial') THEN
    CREATE INDEX "IX_document_chunks_document_id" ON document_chunks (document_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260820060134_Initial') THEN
    CREATE INDEX "IX_financial_snapshots_business_id" ON financial_snapshots (business_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260820060134_Initial') THEN
    CREATE INDEX "IX_loan_payments_loan_id" ON loan_payments (loan_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260820060134_Initial') THEN
    CREATE INDEX "IX_loans_business_id" ON loans (business_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260820060134_Initial') THEN
    CREATE INDEX "IX_recommendations_business_id" ON recommendations (business_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260820060134_Initial') THEN
    CREATE UNIQUE INDEX "IX_refresh_tokens_token" ON refresh_tokens (token);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260820060134_Initial') THEN
    CREATE INDEX "IX_refresh_tokens_user_id" ON refresh_tokens (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260820060134_Initial') THEN
    CREATE INDEX "IX_simulations_business_id" ON simulations (business_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260820060134_Initial') THEN
    CREATE INDEX "IX_transactions_business_id_occurred_at" ON transactions (business_id, occurred_at);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260820060134_Initial') THEN
    CREATE INDEX "IX_transactions_business_id_type" ON transactions (business_id, type);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260820060134_Initial') THEN
    CREATE UNIQUE INDEX "IX_users_email" ON users (email);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260820060134_Initial') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260820060134_Initial', '8.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260822140828_AddUserRoleAndLastLogin') THEN
    ALTER TABLE users ADD last_login_at timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260822140828_AddUserRoleAndLastLogin') THEN
    ALTER TABLE users ADD role integer NOT NULL DEFAULT (0);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260822140828_AddUserRoleAndLastLogin') THEN
    CREATE INDEX "IX_users_role" ON users (role);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260822140828_AddUserRoleAndLastLogin') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260822140828_AddUserRoleAndLastLogin', '8.0.10');
    END IF;
END $EF$;
COMMIT;

